index:
    path: /
    controller: App\Controller\BlogController::index
    defaults:
        page: 1

index_paginated:
    path: /page/{page<[1-9]\d*>}
    controller: App\Controller\BlogController::index